# Generated by Django 5.0.4 on 2024-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=32)),
                ('rent', models.CharField(max_length=32)),
                ('deposit', models.CharField(max_length=32)),
            ],
        ),
    ]
